### ISSUE TITLE
tor_: countries not working, TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by msebald** [munin-monitoring/contrib#1176]
Since upgrading tor_ because of issues mentioned in #1166 tor_countries does not work anymore:

```
munin-run tor_countries
Traceback (most recent call last):
  File "/etc/munin/plugins/tor_countries", line 555, in <module>
    main()
  File "/etc/munin/plugins/tor_countries", line 548, in main
    provider.fetch()
  File "/etc/munin/plugins/tor_countries", line 315, in fetch
    with open(self.cache_dir_name) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

python-geoip and python3-geoip is installed. If you need any further information I am happy to provide these.

**Comment by sumpfralle** [comment]
Thank you for your report!

I think, I fixed the issue now. Please report back, if it is not working for you.

**Comment by msebald** [comment]
@sumpfralle Thank you! Yes, it seems to work, at least it is producing numbers again. :-)

```
munin-run tor_countries
Austria.value 86
Canada.value 327
Finland.value 123
France.value 685
Germany.value 1308
Luxembourg.value 75
Netherlands.value 326
Norway.value 83
Romania.value 92
Russian_Federation.value 178
Sweden.value 173
Switzerland.value 178
United_Kingdom.value 164
United_States.value 1429
Unknown.value 273
```
