### ISSUE TITLE
mongo_lock fails: TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by noradaiko** [munin-monitoring/contrib#652]
```
Error output from mongo_lock:
     Traceback (most recent call last):
       File "/etc/munin/plugins/mongo_lock", line 46, in <module>
         doData()
       File "/etc/munin/plugins/mongo_lock", line 23, in doData
         ratio = float(status["globalLock"]["lockTime"]) / status["globalLock"]["totalTime"]
     TypeError: float() argument must be a string or a number
Service 'mongo_lock' exited with status 1/0.
```

My server is Ubuntu 14.04.3 and MongoDB 2.6.11

**Comment by noradaiko** [comment]
I made PR #653 so close it
